### ISSUE TITLE
mp_uo_dawnville?

### ISSUE THREAD

**Issue by Shady7557** [cato-a/CODPM-MapImages#13]
mp_uo_dawnville seems to be in the custom folder and is not actually the stock UO version of Dawnville. Is this a custom map with the same name that overrides the default UO Dawnville? Because UO's Dawnville is not at night.

**Comment by cato-a** [comment]
Hi

Apparently it is this map: https://vcodmods.com/view/mp_uo_dawnville

This map image will never be loaded on cod.pm because the `mp_uo_dawnville` image is mapped to `mp_dawnville` the stock map image.

You can see the mappings that may be similar on cod.pm in the `mapalias.json` file:

https://github.com/cato-a/CODPM-MapImages/blob/main/mapalias.json

The key is the map image and the values are aliases.

**Comment by Shady7557** [comment]
I fully understand. Thank you for the clarification. That map alias is very useful to have and I didn't notice it before. I'm sorry!
I use the cod.pm API in my application (CoDUO FoV Changer), and right now for map images in the server browser feature it simply drops the _uo_ so mp_uo_carentan becomes mp_carentan, for example. It's the same thing, basically, but not using an actual mapped alias system such as your JSON.
It simply confused me as to why it was in the custom directory (with the name of a default map), but my understanding now is that it's a version of UO's Dawnville for VCoD.

In any case, there's no issue here. All is well. Thanks for your wonderful project and for helping keep these games alive!

**Comment by cato-a** [comment]
Thanks for your comment!

It's nice to see the API being used. I actually added the map image path (with mapping) to the API itself recently. It was on my TODO for a while.

![image](https://github.com/cato-a/CODPM-MapImages/assets/121131666/58546438-042b-4494-ba96-061abeb3ebfd)

I'll check your application on next release. :)
